#ifndef GPIO_CNFG_H
#define GPIO_CNFG_H

#include "GPIO_interface.h"

#define NUMBER_OF_USED_PINS  6

typedef struct
{
	PORT_NAME PORT;
	PIN_NUM PIN;
	PIN_MODE MODE;
	AF_ID_t AF_ID;
	const PUSHPULL_OR_OPENDRAIN TYPE;
	const OUTPUT_SPEED SPEED;
	PULL_UP_DOWN SETTING;
}pinInfo;



static  pinInfo ARRAY_OF_PINS[NUMBER_OF_USED_PINS]=
{

		{PORT_NAME_A ,PIN_NUM_0,OUTPUT,NOT_USED,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

		{PORT_NAME_A ,PIN_NUM_1,OUTPUT,NOT_USED,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

		{PORT_NAME_A ,PIN_NUM_5,AF,AF_SPI1_4,NOT_USED , NOT_USED ,NOT_USED},

		{PORT_NAME_A ,PIN_NUM_7,AF,AF_SPI1_4,NOT_USED , NOT_USED ,NOT_USED},

		{PORT_NAME_B ,PIN_NUM_6,AF,AF_USART1_2 , NOT_USED ,NOT_USED ,NOT_USED},

		{PORT_NAME_B ,PIN_NUM_7,AF,AF_USART1_2 , NOT_USED ,NOT_USED , NOT_USED},


};
/*	{PORT_NAME_B ,PIN_NUM_0,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_B ,PIN_NUM_1,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_B ,PIN_NUM_2,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_B ,PIN_NUM_5,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_B ,PIN_NUM_6,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_B ,PIN_NUM_7,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_A ,PIN_NUM_0,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_A ,PIN_NUM_1,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_A ,PIN_NUM_2,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_A ,PIN_NUM_3,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},

	{PORT_NAME_A ,PIN_NUM_4,OUTPUT,PUSHPULL , OUTPUT_SPEED_VERY_HIGH_SPEED ,NO_PULL_UP_PULL_DOWN},*/

#endif
