#ifndef RCC_INTERFACE
#define RCC_INTERFACE

typedef enum{
	PERIPHRAL_GPIO_A =0,
	PERIPHRAL_GPIO_B,
	PERIPHRAL_GPIO_C,
	PERIPHRAL_GPIO_D,
	PERIPHRAL_GPIO_E,
	PERIPHRAL_GPIO_H,
	PERIPHRAL_CRC ,
	PERIPHRAL_DMA_1,
	PERIPHRAL__DMA_2,
	PERIPHRAL_OTG_FS,
	PERIPHRAL_TIMER_2,
	PERIPHRAL_TIMER_3,
	PERIPHRAL_TIMER_4,
	PERIPHRAL_TIMER_5,
	PERIPHRAL_WWDG,
	PERIPHRAL_SPI_2,
	PERIPHRAL_SPI_3,
	PERIPHRAL_USART_2,
	PERIPHRAL_I2C_1,
	PERIPHRAL_I2C_2,
	PERIPHRAL_I2C_3,
	PERIPHRAL_PWR_INTFC,
	PERIPHRAL_TIMER_1,
	PERIPHRAL_USART_1,
	PERIPHRAL_USART_6,
	PERIPHRAL_ADC_1,
	PERIPHRAL_SDIO,
	PERIPHRAL_SPI_1,
	PERIPHRAL_SPI_4,
	PERIPHRAL_SYSCFG,
	PERIPHRAL_TIMER_9,
	PERIPHRAL_TIMER_10,
	PERIPHRAL_TIMER_11,
	

}PERIPHRAL;
void RCC_voidInit();/*reg CR and CFGR */
void RCC_voidEnablePeripheralClock(PERIPHRAL PeriphralId);/*switch on bus and enable periephral */
void RCC_voidDisablePeripheralClock(PERIPHRAL PeriphralId);



#endif